### ISSUE TITLE
questions about GenerateKeyPair

### ISSUE THREAD

**Issue by zychappy** [wavesplatform/gowaves#66]
one pair keys generated via func GenerateKeyPair
sk,pk
`YoLY4iripseWvtMt29sc89oJnjxzodDgQ9REmEPFHkK  3qTkgmBYFjdSEtib9C4b3yHiEexyJ59A5ZVjSvXsg569`

when I started with this 3qTkgmBYFjdSEtib9C4b3yHiEexyJ59A5ZVjSvXsg569 
then 
```
java.lang.Exception: InvalidAddress(Wrong address string length: max=36, actual: 44)
```
they are really different with recipient of devnet.conf
```
3FgScYB6MNdnN8m4xXddQe1Bjkwmd3U7YtM
3qTkgmBYFjdSEtib9C4b3yHiEexyJ59A5ZVjSvXsg569 (generated)
```
anybody could tell me why?

**Comment by alexeykiselev** [comment]
Hello!
The function `crypto.GenerateKeyPair(seed []byte)` creates public and private keys. You can use those keys to create and verify signatures of transactions, blocks and so on. Also you can produce an address from a public key.

To create an `Address` you have to use the `proto.NewAddressFromPublicKey(scheme byte, publicKey crypto.PublicKey)` function. As you can see it accepts the `scheme` byte, also known as network byte, you have to pass here the `'D'` character if you want to create correct address for DevNet or use a constant `DevNetScheme`. 

```golang
package main

import (
	"fmt"
	"github.com/wavesplatform/gowaves/pkg/crypto"
	"github.com/wavesplatform/gowaves/pkg/proto"
)

func main() {
	pk, _ := crypto.NewPublicKeyFromBase58("3qTkgmBYFjdSEtib9C4b3yHiEexyJ59A5ZVjSvXsg569")
	addr, _ := proto.NewAddressFromPublicKey(proto.DevNetScheme, pk)
	fmt.Println(addr.String())
}
```
This example gives the `3FY5mLyuirMhegsDMVk85c1ZLwStivaV7cd` address. It differs from the expected. I think it's because yours was created from different public key or seed.

**Comment by zychappy** [comment]
oh~ I see,thank you very much! @alexeykiselev
